name: Action测试

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 查看rustc版本
      run: rustc --version
    - name: 查看cargo版本
      run: cargo version
    - name: 查看所在目录
      run: pwd
    - name: 查看目录文件
      run: ll
    - name: 运行
      run: cargo run
