name: Action测试

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    # - name: Set up Rust
    #   uses: actions-rs/toolchain@v1
    #   with:
    #     toolchain: nightly-2023-12-28  # 指定 Rust 版本，nightly-2023-12-28'
    #     override: true
    #     target: aarch64-unknown-none
    #     components: rustfmt, clippy, rust-src, llvm-tools-preview

    # - name: Install cargo-binutils  
    #   run: cargo install cargo-binutils

    # - name: 查看rustc版本
    #   run: rustc --version
    # - name: 查看cargo版本
    #   run: cargo version
    
    # - name: 查看target列表
    #   run: rustup target list
    # - name: Install necessary components  
    #   run: rustup target add aarch64-unknown-none
    # - name: 查看target列表2
    #   run: rustup target list
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3
    # - name: QEMU Version
    #   run: python --version

    - name: pwd
      run: pwd

    - name: ls
      run: ls

    - name: install
      run: sudo apt install python3-venv ninja-build pkg-config python3-pip libglib2.0-dev nettle-dev libpixman-1-dev meson git flex bison libslirp-dev
    
    - name: pip install
      run: pip install sphinx-rtd-theme

    - name: wget
      run: wget  https://download.qemu.org/qemu-9.0.2.tar.xz

    - name: tar
      run: tar xvJf qemu-9.0.2.tar.xz

    - name: Change directory and list files
      run: |  
        cd ./qemu-9.0.2 
        ls -la  
        shell: bash

    - name: ./configure
      run: ./configure --target-list=aarch64-softmmu --enable-kvm --enable-nettle --enable-user --enable-linux-user --enable-slirp --enable-debug

    - name: make
      run: make -j$(nproc)

    - name: install
      run: sudo make install

    - name: version
      run: qemu-system-aarch64 --version

    - name: 查看所在目录
      run: cd action_test

    - name: 查看目录文件
      run: ls

    - name: 运行
      run: cargo run
